package com.co.test.wsdl;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2022-05-30T17:01:48.023-05:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "wstest", 
                  wsdlLocation = "classpath:etc/wsdl/wstest.wsdl",
                  targetNamespace = "http://integracion.coopeuch.cl/wstest/") 
public class Wstest extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://integracion.coopeuch.cl/wstest/", "wstest");
    public final static QName WstestPort = new QName("http://integracion.coopeuch.cl/wstest/", "wstestPort");
    static {
        URL url = Wstest.class.getClassLoader().getResource("etc/wsdl/wstest.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(Wstest.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:etc/wsdl/wstest.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public Wstest(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Wstest(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wstest() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Wstest(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Wstest(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Wstest(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WstestSOAPPortType
     */
    @WebEndpoint(name = "wstestPort")
    public WstestSOAPPortType getWstestPort() {
        return super.getPort(WstestPort, WstestSOAPPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WstestSOAPPortType
     */
    @WebEndpoint(name = "wstestPort")
    public WstestSOAPPortType getWstestPort(WebServiceFeature... features) {
        return super.getPort(WstestPort, WstestSOAPPortType.class, features);
    }

}
