package com.co.test.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by Apache CXF 3.1.9
 * 2022-05-30T17:01:48.020-05:00
 * Generated source version: 3.1.9
 * Author: Ana Aragon
 * 
 */

@Path("/")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)

@WebService(targetNamespace = "http://integracion.coopeuch.cl/wstest/", name = "wstestSOAPPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WstestSOAPPortType {

	@POST
	@Path("consultar")
	@WebMethod(action = "http://integracion.coopeuch.cl/wstest/consultar")
    @WebResult(name = "consultarResponse", targetNamespace = "http://integracion.coopeuch.cl/wstest/", partName = "parameters")
    public ConsultarResponse consultar(
        @WebParam(partName = "parameters", name = "consultarRequest", targetNamespace = "http://integracion.coopeuch.cl/wstest/")
        ConsultarRequest parameters
    );
	@POST
	@Path("crear")
    @WebMethod(action = "http://integracion.coopeuch.cl/wstest/crear")
    @WebResult(name = "crearResponse", targetNamespace = "http://integracion.coopeuch.cl/wstest/", partName = "parameters")
    public CrearResponse crear(
        @WebParam(partName = "parameters", name = "crearRequest", targetNamespace = "http://integracion.coopeuch.cl/wstest/")
        CrearRequest parameters
    );
	@POST
	@Path("actualizar")
    @WebMethod(action = "http://integracion.coopeuch.cl/wstest/actualizar")
    @WebResult(name = "actualizarResponse", targetNamespace = "http://integracion.coopeuch.cl/wstest/", partName = "parameters")
    public ActualizarResponse actualizar(
        @WebParam(partName = "parameters", name = "actualizarRequest", targetNamespace = "http://integracion.coopeuch.cl/wstest/")
        ActualizarRequest parameters
    );
}
